# Generated by Django 3.1.5 on 2021-02-23 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210205_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='connection',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['created_at']},
        ),
    ]
